# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f091d2a86fb6f468aeb68a7b2110fd9bb9b97dc4eb56736557a4bc127170c11dbe467c3e4e68ec69efe809eaf170366cf1dbdc9f269a2423b9b925cf277061f

test:
  secret_key_base: ccfc4cea6666b2b2ae21258d69192048a22604ba4f462884389c71136e4552a980e168ae5974eeecb57b9e87c6cfd60fe1c10e4388cc5980a4df614d2b2c2f1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
